[Appearance]
color_scheme_path=
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
cursor_theme=Bibata-Modern-Ice
icon_theme=Papirus-Dark

[Colors]
# endeavouros theme palette hint
# bg=#1a1b26 fg=#c0caf5 accent=#7aa2f7 accent2=#bb9af7
window=#1a1b26
windowText=#c0caf5
base=#24283b
alternateBase=#16161e
text=#c0caf5
button=#24283b
buttonText=#c0caf5
brightText=#f7768e
highlight=#7aa2f7
highlightedText=#1a1b26
link=#7aa2f7
linkVisited=#bb9af7
