[Appearance]
color_scheme_path=
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
cursor_theme=Bibata-Modern-Classic
icon_theme=gruvbox-dark-icons-gtk

[Colors]
# endeavouros theme palette hint
# bg=#282828 fg=#ebdbb2 accent=#fe8019 accent2=#b8bb26
window=#282828
windowText=#ebdbb2
base=#3c3836
alternateBase=#1d2021
text=#ebdbb2
button=#3c3836
buttonText=#ebdbb2
brightText=#fb4934
highlight=#fe8019
highlightedText=#282828
link=#fe8019
linkVisited=#b8bb26
