# Kitty colors
foreground #cdd6f4
background #1e1e2e
selection_foreground #1e1e2e
selection_background #cba6f7
cursor #cba6f7
cursor_text_color #1e1e2e
url_color #89b4fa

color0  #181825
color1  #f38ba8
color2  #a6e3a1
color3  #fab387
color4  #89b4fa
color5  #cba6f7
color6  #cba6f7
color7  #cdd6f4
color8  #a6adc8
color9  #f38ba8
color10 #a6e3a1
color11 #f5c2e7
color12 #89b4fa
color13 #cba6f7
color14 #89b4fa
color15 #cdd6f4

active_border_color #cba6f7
inactive_border_color #45475a
bell_border_color #f38ba8
