[Appearance]
color_scheme_path=
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
cursor_theme=Bibata-Modern-Ice
icon_theme=Papirus-Dark

[Colors]
# endeavouros theme palette hint
# bg=#1e1e2e fg=#cdd6f4 accent=#cba6f7 accent2=#89b4fa
window=#1e1e2e
windowText=#cdd6f4
base=#313244
alternateBase=#181825
text=#cdd6f4
button=#313244
buttonText=#cdd6f4
brightText=#f38ba8
highlight=#cba6f7
highlightedText=#1e1e2e
link=#cba6f7
linkVisited=#89b4fa
