# NVIDIA-friendly Wayland playback
hwdec=auto-safe
vo=gpu-next
gpu-api=auto
gpu-context=wayland
profile=gpu-hq
keep-open=yes
save-position-on-quit=yes
osc=yes
osd-font="JetBrainsMono Nerd Font"
osd-font-size=28
volume=70
volume-max=150
ytdl-format=bestvideo[height<=?2160]+bestaudio/best
