# Kitty colors
foreground #e8f0ff
background #0d0208
selection_foreground #0d0208
selection_background #00f0ff
cursor #00f0ff
cursor_text_color #0d0208
url_color #ff2a6d

color0  #12050c
color1  #ff2a6d
color2  #39ff14
color3  #ff9f1c
color4  #00f0ff
color5  #bf00ff
color6  #00f0ff
color7  #e8f0ff
color8  #8a9bb0
color9  #ff2a6d
color10 #39ff14
color11 #fcee0a
color12 #00f0ff
color13 #bf00ff
color14 #ff2a6d
color15 #e8f0ff

active_border_color #00f0ff
inactive_border_color #2a1520
bell_border_color #ff2a6d
