[Appearance]
color_scheme_path=
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
cursor_theme=Bibata-Modern-Classic
icon_theme=Papirus-Dark

[Colors]
# endeavouros theme palette hint
# bg=#2d353b fg=#d3c6aa accent=#a7c080 accent2=#e67e80
window=#2d353b
windowText=#d3c6aa
base=#343f44
alternateBase=#232a2e
text=#d3c6aa
button=#343f44
buttonText=#d3c6aa
brightText=#e67e80
highlight=#a7c080
highlightedText=#2d353b
link=#a7c080
linkVisited=#e67e80
