[Appearance]
color_scheme_path=
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
cursor_theme=Bibata-Modern-Ice
icon_theme=Papirus-Dark

[Colors]
# endeavouros theme palette hint
# bg=#191724 fg=#e0def4 accent=#c4a7e7 accent2=#ebbcba
window=#191724
windowText=#e0def4
base=#1f1d2e
alternateBase=#110f1a
text=#e0def4
button=#1f1d2e
buttonText=#e0def4
brightText=#eb6f92
highlight=#c4a7e7
highlightedText=#191724
link=#c4a7e7
linkVisited=#ebbcba
