[Appearance]
color_scheme_path=
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
cursor_theme=Bibata-Modern-Ice
icon_theme=Papirus-Dark

[Colors]
# endeavouros theme palette hint
# bg=#282a36 fg=#f8f8f2 accent=#bd93f9 accent2=#ff79c6
window=#282a36
windowText=#f8f8f2
base=#44475a
alternateBase=#21222c
text=#f8f8f2
button=#44475a
buttonText=#f8f8f2
brightText=#ff5555
highlight=#bd93f9
highlightedText=#282a36
link=#bd93f9
linkVisited=#ff79c6
