[Appearance]
color_scheme_path=
custom_palette=true
standard_dialogs=default
style=Fusion

[Interface]
cursor_theme=Bibata-Modern-Ice
icon_theme=Papirus-Dark

[Colors]
# endeavouros theme palette hint
# bg=#2e3440 fg=#eceff4 accent=#88c0d0 accent2=#81a1c1
window=#2e3440
windowText=#eceff4
base=#3b4252
alternateBase=#242933
text=#eceff4
button=#3b4252
buttonText=#eceff4
brightText=#bf616a
highlight=#88c0d0
highlightedText=#2e3440
link=#88c0d0
linkVisited=#81a1c1
